//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHoa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIET_GIOHANG
    {
        public int MaGH { get; set; }
        public string MaHoa { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual HOA HOA { get; set; }
        public virtual GIOHANG GIOHANG { get; set; }
    }
}
