//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHoa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONHANG
    {
        public DONHANG()
        {
            this.CHITIET_DONHANG = new HashSet<CHITIET_DONHANG>();
            this.KHUYENMAIs = new HashSet<KHUYENMAI>();
        }
    
        public string MaDH { get; set; }
        public string MaKH { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public string DiaChiGiao { get; set; }
        public string TrangThai { get; set; }
    
        public virtual ICollection<CHITIET_DONHANG> CHITIET_DONHANG { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual ICollection<KHUYENMAI> KHUYENMAIs { get; set; }
    }
}
