//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHoa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIOHANG
    {
        public GIOHANG()
        {
            this.CHITIET_GIOHANG = new HashSet<CHITIET_GIOHANG>();
        }
    
        public int MaGH { get; set; }
        public string MaKH { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual ICollection<CHITIET_GIOHANG> CHITIET_GIOHANG { get; set; }
    }
}
