//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHoa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOA
    {
        public HOA()
        {
            this.CHITIET_DONHANG = new HashSet<CHITIET_DONHANG>();
            this.CHITIET_GIOHANG = new HashSet<CHITIET_GIOHANG>();
        }
    
        public string MaHoa { get; set; }
        public string TenHoa { get; set; }
        public string MaLoai { get; set; }
        public decimal Gia { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public string MoTa { get; set; }
        public string HinhAnh { get; set; }
        public string TrangThai { get; set; }
    
        public virtual ICollection<CHITIET_DONHANG> CHITIET_DONHANG { get; set; }
        public virtual LOAIHOA LOAIHOA { get; set; }
        public virtual ICollection<CHITIET_GIOHANG> CHITIET_GIOHANG { get; set; }
    }
}
