//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHoa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHUYENMAI
    {
        public KHUYENMAI()
        {
            this.DONHANGs = new HashSet<DONHANG>();
        }
    
        public string MaKM { get; set; }
        public string TenKM { get; set; }
        public Nullable<int> PhanTramGiam { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public string DieuKien { get; set; }
    
        public virtual ICollection<DONHANG> DONHANGs { get; set; }
    }
}
